### ISSUE TITLE
Update for HELICS 2.2.0

### ISSUE THREAD

**Issue by phlptp** [GMLC-TDC/helics-conda#4]
conda needs to be updated to HELICS 2.2.0

**Comment by kdheepak** [comment]
When [these builds](https://travis-ci.com/GMLC-TDC/helics-conda/builds/125337406) pass we can close this.

**Comment by kdheepak** [comment]
[All files have been uploaded](https://anaconda.org/gmlc-tdc/helics/files) even though one travis job didn't finish correctly.
